CHECK FILE podman_sock with path /run/podman/podman.sock
  if does not exists then restart
  if failed permission 660 then exec "/bin/chmod 660 /run/podman/podman.sock"
  if failed gid wheel then exec "/bin/chgrp wheel /run/podman/podman.sock"
  start program  "/etc/init.d/podman start"
  stop  program  "/etc/init.d/podman stop"
  if 5 restarts within 5 cycles then timeout
  depends on podman_bin
check file podman_bin with path /usr/bin/podman
    if failed permission 755 then unmonitor
