CHECK SYSTEM $HOST_uptime
   if uptime > 180 days then alert every 33 cycles

CHECK SYSTEM $HOST
   if cpu usage (user) > 70% then alert
   if cpu usage (system) > 30% then alert
   if loadavg (1min) > 3 then alert
   if loadavg (5min) > 2 then alert
   if memory usage > 75% then alert
   if swap usage > 25% then alert
   if cpu usage (wait) > 20% then alert
   if filedescriptors > 5000 then alert

CHECK FILESYSTEM rootfs with path "/"
   if space usage > 90% then alert 
CHECK FILESYSTEM rootfs with path "/var"
   if space usage > 80% then alert
 
CHECK PROCESS cronie with pidfile /run/cronie.pid
   start program = "/etc/init.d/cronie start" 
   stop program = "/etc/init.d/cronie stop" 
   if totalmem > 600.0 MB for 3 cycles then restart 
   if 3  restarts within 5 cycles then timeout
   depends on cronie_bin
check file cronie_bin with path /usr/sbin/crond
    if failed permission 755 then unmonitor

CHECK PROCESS chronyd with pidfile /run/chrony/chronyd.pid
   start program = "/etc/init.d/chronyd start" 
   stop program = "/etc/init.d/chronyd stop" 
   if totalmem > 600.0 MB for 3 cycles then restart 
   depends on chronyd_bin
check file chronyd_bin with path /usr/sbin/chronyd
    if failed permission 755 then unmonitor

check process haveged with pidfile /var/run/haveged.pid
    start "/etc/init.d/haveged start"
    stop  "/etc/init.d/haveged stop"
    depends on haveged_bin
check file haveged_bin with path /usr/sbin/haveged
    if failed permission 755 then unmonitor
 
